# Generated by Django 4.2.2 on 2023-09-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('INBOX_STATUS', 'Inbox'), ('DRAFT_STATUS', 'Draft'), ('SENT_STATUS', 'Sent'), ('SPAM_STATUS', 'Spam')], max_length=60),
        ),
    ]
