# Generated by Django 4.2.2 on 2023-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.IntegerField(choices=[(1, 'Inbox'), (2, 'Draft'), (3, 'Sent'), (4, 'Spam')], default=1),
        ),
    ]
