# Generated by Django 4.2.2 on 2023-08-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_projectstatstics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatstics',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ongoing'), (2, 'Completed')], default=1),
        ),
    ]
